"""
NoorGuard Ultimate - Schemas
Pydantic Models
"""

from app.schemas.user import (
    UserLogin,
    UserRegister,
    RefreshTokenRequest,
    TokenResponse,
    UserResponse,
    UserUpdate,
    ChangePassword,
    PasswordResetRequest,
    PasswordResetConfirm,
    DeviceRegister,
    DeviceUpdate,
    DeviceResponse,
    DeviceLocation,
    NotificationResponse,
    NotificationMarkRead,
    MessageResponse,
    ErrorResponse,
    PaginatedResponse,
    HealthCheckResponse,
    UserRole
)

from app.schemas.child import (
    ChildCreate,
    ChildUpdate,
    ChildResponse,
    ChildListResponse,
    ChildStatusUpdate,
    ActivityCreate,
    ActivityResponse,
    ActivityListResponse,
    BlockedAttemptCreate,
    BlockedAttemptResponse,
    BlockedAttemptListResponse,
    ScreenTimeLogCreate,
    ScreenTimeLogResponse,
    DailyScreenTimeResponse,
    ScreenTimeAnalyticsResponse,
    AppUsageCreate,
    AppUsageResponse,
    AppUsageListResponse,
    AnalyticsOverview,
    RiskAssessment,
    WeeklyReport,
    FilterLevel,
    ChildStatus
)

__all__ = [
    # User schemas
    "UserLogin",
    "UserRegister",
    "RefreshTokenRequest",
    "TokenResponse",
    "UserResponse",
    "UserUpdate",
    "ChangePassword",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "DeviceRegister",
    "DeviceUpdate",
    "DeviceResponse",
    "DeviceLocation",
    "NotificationResponse",
    "NotificationMarkRead",
    "MessageResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "HealthCheckResponse",
    "UserRole",
    # Child schemas
    "ChildCreate",
    "ChildUpdate",
    "ChildResponse",
    "ChildListResponse",
    "ChildStatusUpdate",
    "ActivityCreate",
    "ActivityResponse",
    "ActivityListResponse",
    "BlockedAttemptCreate",
    "BlockedAttemptResponse",
    "BlockedAttemptListResponse",
    "ScreenTimeLogCreate",
    "ScreenTimeLogResponse",
    "DailyScreenTimeResponse",
    "ScreenTimeAnalyticsResponse",
    "AppUsageCreate",
    "AppUsageResponse",
    "AppUsageListResponse",
    "AnalyticsOverview",
    "RiskAssessment",
    "WeeklyReport",
    "FilterLevel",
    "ChildStatus"
]
